version: '3.8'

services:
  users:
    image: luisdlr11/api_users:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - MONGO_URI=
      - SALT=3ODk
    command: 'python3 __init__.py'